package com.pilaf.warhammerstats;

public enum Skills {

    CAUSE_FEAR, CAUSE_TERROR, MAGICAL_ATTACK, FIRE_ATTACK, IMMUNE_TO_PSYCHOLOGY, CHARGE_DEFENCE_AGAINST_LARGE, CHARGE_DEFENCE_EXPERT, UNBREAKABLE, UNDEAD;
}
